# Generated by Django 5.0.4 on 2024-04-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oracles", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SixOracleChoices",
            new_name="OracleAnswers",
        ),
    ]
