# Generated by Django 5.0.4 on 2024-04-19 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oracles", "0002_rename_sixoraclechoices_oracleanswers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OracleAnswers",
            new_name="OracleAnswer",
        ),
    ]
