# Generated by Django 5.0.4 on 2024-04-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracles", "0003_rename_oracleanswers_oracleanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="oracleanswer",
            name="roll_value",
            field=models.IntegerField(default=0),
        ),
    ]
