# Generated by Django 5.0.4 on 2024-04-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracles", "0004_oracleanswer_roll_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oraclequestion",
            name="pub_date",
        ),
        migrations.AddField(
            model_name="oraclequestion",
            name="category",
            field=models.CharField(default="General", max_length=200),
        ),
        migrations.AlterField(
            model_name="oracleanswer",
            name="roll_value",
            field=models.IntegerField(default=1),
        ),
    ]
