# Generated by Django 5.0.4 on 2024-04-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracles", "0005_remove_oraclequestion_pub_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oraclequestion",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
