# Generated by Django 5.0.4 on 2024-04-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oracles", "0006_oraclequestion_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oracleanswer",
            name="roll_value",
            field=models.IntegerField(default=0),
        ),
    ]
